#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII 

bspc config border_width         0
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a firefox desktop=^2
bspc rule -a google-chrome-stable desktop=^2
bspc rule -a termite desktop=^3 state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a emacs state=tilling
bspc rule -a Screenkey manage=off
bspc rule -a Thunar desktop=^4 
bspc rule -a discord desktop=^1
bspc rule -a Spotify desktop=^6
bspc rule -a steam-runtime desktop=^5
bspc rule -a steam-native desktop=^5
bspc rule -a steam desktop=^5
bspc rule -a Steam desktop=^5

feh --bg-scale ~/.wallpaper.jpg 
$HOME/.config/polybar/launch.sh
compton &
discord &
mpd &
steam-runtime
